name: Reusable CI

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.10"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Build (simulate)
      run: |
        echo "🛠️ Simulating build process..."
        mkdir -p build
        echo "hello" > build/output.txt

    - name: Run tests
      run: pytest
