name: Story Template by yml
description: Story test template
# title: "[Bug]: "
# labels: ["bug", "triage"]
projects: ["chiaoooo/3"]
# assignees:
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: |
        - 身為產品內部的角色（如 Admin、Tenant admin、Tenant user），
        - 我希望能實現某項功能，來達成特定的產品目標。
    # placeholder: |
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Acceptance Criteria
      description: 針對該功能實現的具體內容與步驟，必須達到指定的驗收標準才算完成。
      placeholder: 可使用 tasklist 呈現
    validations:
      required: true
  - type: textarea
    id: task_list
    attributes:
      label: Relationship
      description: |
        - Blocks / Is blocked by：特別適用於 Spike，因為 Spike 可能會阻塞後續 Story 的開發。
        - Relates to：適用於所有類型，表示有關聯但無嚴格依賴。
        - Parent / Sub-task：在 Story 裡特別常用，Task 常是 Sub-task。
    # placeholder: |
    #   - [ ] 撰寫 API 文件
    #   - [ ] 建立資料表
    #   - [ ] 寫測試
