name: PR CI (Call Reusable)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  check-pr-source:
    uses: ./.github/workflows/check-pr-source.yml
    with:
      base_branch: main
      disallowed_source_prefix: release/

  run-ci:
    needs: check-pr-source
    uses: ./.github/workflows/build-test.yml
    # with:
    #   python-version: "3.10"
